"""comment

Revision ID: 1164dc7769bd
Revises: cbf74ac8f61c
Create Date: 2017-11-13 23:54:30.142011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1164dc7769bd'
down_revision = 'cbf74ac8f61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obs_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obs_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('account_num', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('pwd', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('test', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
