"""empty message

Revision ID: 83da7af28019
Revises: a117f99c2ada
Create Date: 2017-11-29 19:21:25.459239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83da7af28019'
down_revision = 'a117f99c2ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('img_path_back', sa.String(length=255), nullable=False))
    op.add_column('deposit', sa.Column('img_path_front', sa.String(length=255), nullable=False))
    op.drop_column('deposit', 'img_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('img_path', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('deposit', 'img_path_front')
    op.drop_column('deposit', 'img_path_back')
    # ### end Alembic commands ###
