"""empty message

Revision ID: 8dfae55d3a2c
Revises: 83da7af28019
Create Date: 2017-11-29 20:39:35.636276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfae55d3a2c'
down_revision = '83da7af28019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('balance_snapshot', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'balance_snapshot')
    # ### end Alembic commands ###
