"""update

Revision ID: a117f99c2ada
Revises: d9f6f5316717
Create Date: 2017-11-22 21:11:00.180065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a117f99c2ada'
down_revision = 'd9f6f5316717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('memo', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    op.drop_column('deposit', 'memo')
    # ### end Alembic commands ###
