"""empty message

Revision ID: a2ebb6a57156
Revises: 8dfae55d3a2c
Create Date: 2017-12-08 16:36:45.633354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ebb6a57156'
down_revision = '8dfae55d3a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone2', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone2'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone2')
    # ### end Alembic commands ###
