"""comment

Revision ID: d9f6f5316717
Revises: ac1d6db37341
Create Date: 2017-11-14 14:04:06.781968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f6f5316717'
down_revision = 'ac1d6db37341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'transfer_ibfk_2', 'transfer', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'transfer_ibfk_2', 'transfer', 'account', ['to_account'], ['account_num'])
    # ### end Alembic commands ###
